language: node_js
node_js:
  - lts/*
install:
  - cd build_docs
  - npm ci
script:
  - cd build_docs
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: chend0316/chend0316.github.io
  target_branch: master
  on:
    branch: master
