language: node_js
node_js:
  - lts/*
install:
  - npm ci --prefix ./build_docs
script:
  - npm run build --prefix ./build_docs
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: chend0316/chend0316.github.io
  target_branch: master
  on:
    branch: master
